// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDQED7eEVEt7FwCvksPMGDKIdd6670DE4',
    appId: '1:629963230157:web:cfcab88848acce61575284',
    messagingSenderId: '629963230157',
    projectId: 'notificationapp-e77ef',
    authDomain: 'notificationapp-e77ef.firebaseapp.com',
    storageBucket: 'notificationapp-e77ef.firebasestorage.app',
    measurementId: 'G-ZFFG8B1V73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNHnryfSsLdihtT3wFFKTyJOYf7-CeGuc',
    appId: '1:629963230157:android:84bfd0cb1857e628575284',
    messagingSenderId: '629963230157',
    projectId: 'notificationapp-e77ef',
    storageBucket: 'notificationapp-e77ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJKrIYEWkFVnWLIyhWYarFdwdahBELNaM',
    appId: '1:629963230157:ios:da83fe10b77ef284575284',
    messagingSenderId: '629963230157',
    projectId: 'notificationapp-e77ef',
    storageBucket: 'notificationapp-e77ef.firebasestorage.app',
    iosBundleId: 'com.example.notificationService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJKrIYEWkFVnWLIyhWYarFdwdahBELNaM',
    appId: '1:629963230157:ios:da83fe10b77ef284575284',
    messagingSenderId: '629963230157',
    projectId: 'notificationapp-e77ef',
    storageBucket: 'notificationapp-e77ef.firebasestorage.app',
    iosBundleId: 'com.example.notificationService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDQED7eEVEt7FwCvksPMGDKIdd6670DE4',
    appId: '1:629963230157:web:4379edbd5c33ac92575284',
    messagingSenderId: '629963230157',
    projectId: 'notificationapp-e77ef',
    authDomain: 'notificationapp-e77ef.firebaseapp.com',
    storageBucket: 'notificationapp-e77ef.firebasestorage.app',
    measurementId: 'G-V6Z4H7Z9VW',
  );
}
